name: Terraform Apply

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
     
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        TF_ACTION_WORKING_DIR: '../terraform'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      env:
        TF_ACTION_WORKING_DIR: '../terraform'    
      run: terraform validate

    - name: Terraform apply
      env:
        TF_ACTION_WORKING_DIR: '../terraform'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false
