name: 'Terraform GitHub Actions'
defaults:
  run:
    working-directory: "terraform"

on:
  - pull_request
  - push

jobs:
  terraform:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_329066851743 }}
        role-duration-seconds: 1200
        aws-region: eu-west-1
      
    - name: Install Terraform
      id: utilities
      run: sudo yum install -y jq yum-utils && sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo && sudo yum -y install terraform
  
    - name: Verify Terraform version
      id: version
      run: terraform --version
      
#    - name: Assume Role
#      id: assume_role
#      run: sh ./script.sh ${{ secrets.AWS_ROLE_TO_ASSUME_550341143323 }}

    - name: Assume Role
#      if: github.event_name == 'pull_request'
      env:
        ROLE: ${{ secrets.AWS_ROLE_TO_ASSUME_550341143323 }}
      run: |
        temp_role=$(aws sts assume-role --role-arn ${ROLE} --role-session-name AWS_ROLE_TO_ASSUME)
        export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
        export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
        export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
        echo "Current Assume role is:" && aws sts get-caller-identity > /tmp/roles.txt
        terraform init
        terraform apply -auto-approve
