name: 'Terraform GitHub Actions'
defaults:
  run:
    working-directory: "terraform"

on:
  - pull_request
  - push

jobs:
  terraform:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v1
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.25

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_329066851743 }}
        role-duration-seconds: 1200
        aws-region: eu-west-1

    - name: Verify Terraform version
      id: version
      run: terraform --version
      
#    - name: Install Terraform
#      id: utilities
#      run: sudo yum install -y jq yum-utils && sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo && sudo yum -y install terraform

    - name: Install utilities
      id: util
      run: sudo yum install -y jq
      
    - name: Assume Role
      id: assume_role
      run: sh ./script.sh ${{ secrets.AWS_ROLE_TO_ASSUME_550341143323 }}
