name: 'Terraform GitHub Actions'
defaults:
  run:
    working-directory: "terraform"

on:
  - pull_request
  - push

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v1
     
    - name: Verify Terraform version
      id: version
      run: terraform --version

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      
    - name: Terraform Init
      id: init        
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate    
      run: terraform validate
      
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true      

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
